apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: namespace-workflow-1678821462707
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80